AllCops:
  TargetRubyVersion: 2.5

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Layout/IndentFirstArrayElement:
  IndentationWidth: 4

Layout/IndentFirstHashElement:
  IndentationWidth: 4

Layout/IndentFirstArgument:
  IndentationWidth: 4

Layout/ClosingParenthesisIndentation:
  Enabled: false
